// Bilingual content dictionary (ES default, EN for the expat/tourist clientele).
// Every visible string lives here so components stay language-agnostic.
// Prices and phone numbers are language-independent and stay in business.ts / here as-is.

export type Lang = "es" | "en" | "fr" | "de";

export const LANG_PATHS: Record<Lang, string> = {
  es: "/",
  en: "/en",
  fr: "/fr",
  de: "/de",
};

export const LANG_LABELS: Record<Lang, string> = {
  es: "ES",
  en: "EN",
  fr: "FR",
  de: "DE",
};

export const content = {
  es: {
    nav: [
      { href: "#sobre", label: "Sobre" },
      { href: "#especialidades", label: "Especialidades" },
      { href: "#precios", label: "Precios" },
      { href: "#reserva", label: "Reservar" },
      { href: "#por-que", label: "Por qué" },
      { href: "#opiniones", label: "Opiniones" },
      { href: "#preguntas", label: "Preguntas" },
      { href: "#ubicacion", label: "Ubicación" },
      { href: "#contacto", label: "Contacto" },
    ],
    navReserve: "Reservar",
    hero: {
      badge: "Barbería · Tenerife",
      title1: "Entra. Siéntate.",
      title2: "Sal con estilo.",
      subtitle1: "Barbería en Tenerife. Cortes, barba y afeitado clásico,",
      subtitle2: "con la atención que te mereces.",
      ctaReserve: "Reservar cita",
      seePrices: "↓ Ver todos los precios",
      badges: ["Cortes y degradados", "Reserva online", "Valorado por sus clientes"],
    },
    video: {
      eyebrow: "En Instagram",
      title: "Míranos en acción",
      subtitle:
        "Cortes, degradados y barba en vídeo. Echa un vistazo a nuestro Instagram y mira cómo trabajamos en el día a día.",
      hint: "@edustyle4 en Instagram",
      cta: "Ver en Instagram",
    },
    about: {
      eyebrow: "Sobre nosotros",
      title: "No es solo un corte. Es tu imagen.",
      p1: "En Eduardo Style tratamos cada cliente como se merece: sin prisas, escuchando lo que buscas y cuidando cada detalle. Cortes de pelo, arreglo de barba, afeitado clásico a navaja y diseños personalizados, todo en un ambiente cercano y relajado.",
      p2: "Da igual si vienes a por tu corte de siempre o quieres cambiar de look por completo: te aconsejamos lo que mejor te queda y lo hacemos con la técnica y el mimo que se merece tu imagen.",
      p3strong: "Reservar es fácil: elige tu hora online y listo.",
      values: [
        { icon: "UserCog", title: "Oficio", description: "Años detrás de la silla. Cada corte, cada barba y cada degradado hecho con técnica y buen pulso." },
        { icon: "HeartHandshake", title: "Cercanía", description: "Aquí no eres un número. Te escuchamos, entendemos tu estilo y te aconsejamos lo que de verdad te queda bien." },
        { icon: "Sparkles", title: "Detalle", description: "Toalla caliente, líneas limpias y acabados cuidados. Sales con la sensación de haberte cuidado de verdad." },
      ],
    },
    specialties: {
      eyebrow: "Nuestras especialidades",
      title: "Lo que más nos piden en Tenerife",
      items: [
        { icon: "Wand2", title: "Diseños y arreglos de barba en Tenerife", description: "Perfilado, arreglo a navaja y máquina, y diseños de barba adaptados a la forma de tu cara. Uno de los servicios que más pedimos en la barbería." },
        { icon: "Waves", title: "Peinados a la moda para hombre en Tenerife", description: "Degradados, texturizados y los estilos que se llevan ahora, adaptados a tu tipo de pelo y a tu día a día." },
        { icon: "Ruler", title: "Cortes de pelo personalizados en Tenerife", description: "Nada de cortes genéricos: estudiamos la forma de tu cara y tu pelo para darte un corte hecho a tu medida." },
      ],
    },
    whyUs: {
      eyebrow: "Por qué Eduardo Style",
      title: "Cuatro razones para sentarte en nuestra silla",
      reasons: [
        { icon: "Scissors", title: "Cortes a tu medida", description: "Degradados, clásicos, diseños y barba trabajada. Adaptamos cada corte a tu tipo de pelo y a tu estilo." },
        { icon: "CalendarCheck", title: "Reserva sin llamadas", description: "Pide tu cita por WhatsApp cuando quieras, incluso fuera del horario. Te confirmamos en minutos." },
        { icon: "Star", title: "Clientes que repiten", description: "La mayoría de quienes prueban Eduardo Style vuelven. Buen trato, buen ambiente y un acabado que se nota." },
        { icon: "MapPin", title: "En tu zona, en Tenerife", description: "Fácil de encontrar y con ese trato de barbería de barrio en el que te sientes como en casa." },
      ],
    },
    testimonials: {
      eyebrow: "Opiniones",
      title: "Lo que dicen nuestros clientes",
      badge: "Reseñas verificadas de Google",
      items: [
        { name: "Symka K.", rating: 5, text: "¡Encantada con el resultado! Eduardo es un peluquero PRO, salí pareciendo modelo 😎", service: "Corte de pelo" },
        { name: "Luc H.", rating: 5, text: "Servicio genial, amable y muy detallista. ¡Lo recomiendo sin dudarlo!", service: "Corte de pelo" },
        { name: "Idayra S.", rating: 5, text: "Eduardo es un profesional estupendo. Le cortó el pelo a mi hijo de tres años, que odia que le corten el pelo, y lo hizo con tanta calma y cariño que no sufrió nada. Totalmente recomendable.", service: "Corte niño" },
        { name: "Fran O.", rating: 5, text: "No he estado en una barbería más eficiente. Los chicos son súper amables y trabajan genial y rápido. No iría a otro sitio, los recomiendo de corazón.", service: "Corte de pelo" },
        { name: "Jack", rating: 5, text: "Servicio excelente. Eduardo es muy profesional, atento y detallista. Entendió perfectamente lo que quería y el resultado me encantó. Repetiré seguro.", service: "Corte de pelo" },
        { name: "Carl-Fredrik B.", rating: 5, text: "Fui a arreglarme el pelo y la barba y encontré, justo a las afueras del centro de Los Abrigos, a un barbero con mucho talento y muy buen precio. Le dedicaron tiempo de verdad a mi pelo y afeitado, salí sintiéndome muy bien cuidado.", service: "Corte + Barba" },
      ],
    },
    prices: {
      eyebrow: "Precios",
      title: "Tarifas claras. Sin sorpresas.",
      subtitle:
        "Estos son nuestros servicios y precios. ¿Dudas sobre lo que necesitas? Escríbenos y te asesoramos.",
      note: "Los precios pueden variar según el largo y el tipo de pelo. ¿Dudas sobre lo que necesitas? Pregúntanos sin compromiso.",
      cta: "Reservar cita",
      groups: [
        { title: "Cortes", items: [
          { name: "Corte de niño", desc: "Hasta 8 años", price: "10 €" },
          { name: "Corte de caballero", desc: "A tijera o máquina", price: "13 €" },
          { name: "Corte + lavado", desc: "Con lavado y peinado", price: "15 €" },
        ] },
        { title: "Corte y barba", items: [
          { name: "Barba a máquina", desc: "Repaso rápido", price: "5 €" },
          { name: "Barba: afeitado o perfilado", desc: "Con toalla caliente", price: "10 €" },
          { name: "Corte + barba", desc: "El más pedido", price: "20 €", highlight: true },
          { name: "Corte + barba + lavado", desc: "Con lavado incluido", price: "23 €" },
          { name: "Corte + barba premium", desc: "Con color, mechas o extras", price: "25 €" },
          { name: "Pack completo", desc: "Corte, barba, cera nariz y orejas, lavado, limpieza facial y masaje", price: "40 €" },
        ] },
        { title: "Color, mechas y extras", items: [
          { name: "Color de barba", desc: "", price: "15 €" },
          { name: "Color de cabello", desc: "", price: "20 €" },
          { name: "Mechas", desc: "", price: "25 €" },
          { name: "Mechas + color", desc: "", price: "35 €" },
          { name: "Decoloración + matiz", desc: "", price: "30 €" },
          { name: "Doble decoloración + matiz", desc: "", price: "40 €" },
          { name: "Cera nariz y orejas", desc: "", price: "5 €" },
          { name: "Lavado", desc: "", price: "3 €" },
        ] },
      ],
    },
    booking: {
      eyebrow: "Reserva online",
      title: "Elige tu hora. Reserva al instante.",
      subtitle:
        "Selecciona servicio, día y hora. Te enviamos un SMS de recordatorio una hora antes de tu cita.",
      serviceLabel: "Servicio",
      servicePlaceholder: "Elige un servicio",
      dayLabel: "Día",
      dayPlaceholder: "Elige un día",
      timeLabel: "Hora",
      timePlaceholder: "Elige una hora",
      unavailableMsg: "La reserva online no está disponible en este momento. Inténtalo de nuevo más tarde.",
      incompleteHint: "Elige servicio, día y hora para continuar.",
      // Real (calendar-backed) booking flow
      nameLabel: "Tu nombre",
      namePlaceholder: "Nombre y apellido",
      phoneLabel: "Teléfono",
      phonePlaceholder: "Tu número",
      confirmBtn: "Reservar cita",
      loadingSlots: "Buscando huecos…",
      noSlots: "No quedan huecos ese día. Prueba otro día.",
      successTitle: "¡Cita reservada!",
      successBody: "Te esperamos el {day} a las {time}.",
      againBtn: "Reservar otra cita",
      takenMsg: "Ese hueco se acaba de ocupar. Elige otra hora, por favor.",
      invalidPhoneMsg: "Revisa tu número de teléfono, no parece correcto.",
      errorMsg: "No se pudo completar la reserva. Inténtalo de nuevo.",
    },
    faq: {
      eyebrow: "Preguntas frecuentes",
      title: "Preguntas frecuentes. Respuestas claras.",
      subtitle:
        "Respuestas rápidas a lo que más nos preguntan. ¿No encuentras lo que buscas? Llámanos.",
      items: [
        { question: "¿Necesito pedir cita o puedo ir directamente?", answer: "Puedes pasarte sin cita, pero para no esperar te recomendamos reservar online. Te confirmamos la hora al instante y te guardamos el hueco." },
        { question: "¿Cómo reservo una cita?", answer: "Lo más rápido es reservar online: eliges servicio, día y hora, y te llega un recordatorio por SMS una hora antes. También puedes llamarnos directamente al +34 694 20 07 78." },
        { question: "¿Cuánto cuesta un corte?", answer: "Un corte de caballero cuesta 13 € y el pack corte + barba 20 €. Los niños 10 €. Tienes la lista completa en la sección de Precios. El precio final puede variar según el largo del pelo." },
        { question: "¿Cortáis a niños?", answer: "Sí. Hacemos cortes para niños con mucha paciencia y buen ambiente, para que la experiencia sea fácil y agradable también para los más pequeños." },
        { question: "¿Hacéis afeitado a navaja?", answer: "Sí. Ofrecemos el afeitado clásico a navaja con toalla caliente: apurado, relajante y con un acabado perfecto. Todo un clásico que merece la pena probar." },
        { question: "¿Qué formas de pago aceptáis?", answer: "Aceptamos pago en efectivo y con tarjeta, lo que te resulte más cómodo." },
        { question: "¿Dónde estáis y qué horario tenéis?", answer: "Estamos en Los Abrigos, en el sur de Tenerife, en la Calle La Marina, Local 1 (38618). El horario es de Lunes a Viernes de 10:00 a 14:00 y de 15:00 a 19:00, y Sábados de 07:00 a 14:00. Los Domingos permanecemos cerrados." },
      ],
    },
    location: {
      eyebrow: "Cómo llegar",
      title: "Ven a vernos",
      subtitle: "Estamos en Tenerife, fácil de encontrar. Pásate o reserva antes tu cita para no esperar.",
      addressLabel: "Dirección",
      phoneLabel: "Teléfono",
      hoursLabel: "Horario",
      closed: "Cerrado",
      reserveBtn: "Reservar cita",
      callBtn: "Llamar",
      mapsBtn: "Abrir en Google Maps",
    },
    contact: {
      eyebrow: "Reserva tu cita",
      title1: "Tu próximo corte,",
      titleAccent: "a un clic",
      subtitle:
        "Reserva tu cita online o llámanos directamente. Confirmamos tu hueco al instante.",
      reserveBtn: "Reservar cita",
      note: "Solemos responder en pocos minutos durante el horario de apertura",
    },
    footer: {
      tagline: "Barbería en Tenerife. Cortes, barba y afeitado clásico, con la atención que te mereces.",
      navTitle: "Navegación",
      contactTitle: "Contacto",
      followTitle: "Síguenos",
      rights: "Todos los derechos reservados.",
      privacy: "Política de privacidad",
      legal: "Aviso legal",
      nav: [
        { href: "#sobre", label: "Sobre nosotros" },
        { href: "#precios", label: "Precios" },
        { href: "#opiniones", label: "Opiniones" },
        { href: "#preguntas", label: "Preguntas" },
        { href: "#ubicacion", label: "Ubicación" },
        { href: "#contacto", label: "Contacto" },
      ],
    },
    days: {
      Lunes: "Lunes", Martes: "Martes", Miércoles: "Miércoles", Jueves: "Jueves",
      Viernes: "Viernes", Sábado: "Sábado", Domingo: "Domingo",
    } as Record<string, string>,
  },

  en: {
    nav: [
      { href: "#sobre", label: "About" },
      { href: "#especialidades", label: "Specialties" },
      { href: "#precios", label: "Prices" },
      { href: "#reserva", label: "Book" },
      { href: "#por-que", label: "Why us" },
      { href: "#opiniones", label: "Reviews" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Location" },
      { href: "#contacto", label: "Contact" },
    ],
    navReserve: "Book",
    hero: {
      badge: "Barbershop · Tenerife",
      title1: "Walk in. Sit down.",
      title2: "Walk out sharp.",
      subtitle1: "Barbershop in Tenerife. Cuts, beard and classic shave,",
      subtitle2: "with the care you deserve.",
      ctaReserve: "Book now",
      seePrices: "↓ See all prices",
      badges: ["Cuts & fades", "Book online", "Loved by customers"],
    },
    video: {
      eyebrow: "On Instagram",
      title: "See us in action",
      subtitle:
        "Cuts, fades and beard work on video. Take a look at our Instagram and see how we work day to day.",
      hint: "@edustyle4 on Instagram",
      cta: "View on Instagram",
    },
    about: {
      eyebrow: "About us",
      title: "It's not just a haircut. It's your look.",
      p1: "At Eduardo Style we treat every client the way they deserve: no rush, listening to what you want and taking care of every detail. Haircuts, beard trims, classic straight-razor shaves and custom designs, all in a friendly, relaxed atmosphere.",
      p2: "Whether you come for your usual cut or want a complete change of look, we advise you on what suits you best and do it with the skill and care your image deserves.",
      p3strong: "Booking is easy: pick your time online and you're done.",
      values: [
        { icon: "UserCog", title: "Craft", description: "Years behind the chair. Every cut, beard and fade done with technique and a steady hand." },
        { icon: "HeartHandshake", title: "Personal", description: "Here you're not a number. We listen, understand your style and advise you on what really suits you." },
        { icon: "Sparkles", title: "Detail", description: "Hot towel, clean lines and careful finishes. You leave feeling genuinely looked after." },
      ],
    },
    specialties: {
      eyebrow: "Our specialties",
      title: "What we're asked for most in Tenerife",
      items: [
        { icon: "Wand2", title: "Beard grooming and designs in Tenerife", description: "Shaping, razor and clipper work, and beard designs tailored to your face shape. One of the most requested services at the barbershop." },
        { icon: "Waves", title: "Trendy men's hairstyles in Tenerife", description: "Fades, texture cuts and the styles people are wearing right now, adapted to your hair type and everyday life." },
        { icon: "Ruler", title: "Personalised haircuts in Tenerife", description: "No generic cuts: we study your face shape and hair to give you a cut made to fit you." },
      ],
    },
    whyUs: {
      eyebrow: "Why Eduardo Style",
      title: "Four reasons to sit in our chair",
      reasons: [
        { icon: "Scissors", title: "Cuts made for you", description: "Fades, classics, designs and worked beards. We adapt every cut to your hair type and style." },
        { icon: "CalendarCheck", title: "Book without calling", description: "Request your appointment on WhatsApp whenever you like, even after hours. We confirm within minutes." },
        { icon: "Star", title: "Clients who come back", description: "Most people who try Eduardo Style return. Great service, great atmosphere and a finish you can see." },
        { icon: "MapPin", title: "Right here in Tenerife", description: "Easy to find, with that neighbourhood-barbershop feel where you're right at home." },
      ],
    },
    testimonials: {
      eyebrow: "Reviews",
      title: "What our clients say",
      badge: "Verified Google reviews",
      items: [
        { name: "Symka K.", rating: 5, text: "Waw, could not be more satisfied — Eduardo is a PRO hairdresser and I look like a model now 😎", service: "Haircut" },
        { name: "Luc H.", rating: 5, text: "Great service, friendly and thorough. I definitely recommend this place!", service: "Haircut" },
        { name: "Idayra S.", rating: 5, text: "Eduardo is a fantastic professional. He cut my three-year-old son's hair — my son hates haircuts — and spoke to him so gently that he didn't suffer at all. Highly recommended.", service: "Kids' cut" },
        { name: "Fran O.", rating: 5, text: "I've never been to a more efficient barbershop. The guys are very friendly and work incredibly well and quickly. I wouldn't go anywhere else.", service: "Haircut" },
        { name: "Jack", rating: 5, text: "Excellent service. Eduardo is very professional, attentive, and detail-oriented. He understood perfectly what I wanted, and I loved the result. I will definitely return.", service: "Haircut" },
        { name: "Carl-Fredrik B.", rating: 5, text: "It was time to trim my hair and style my beard, and just outside the center of Los Abrigos I found this talented and very affordable barber. They really took their time and I felt more than well taken care of.", service: "Cut + Beard" },
      ],
    },
    prices: {
      eyebrow: "Prices",
      title: "Clear prices. No surprises.",
      subtitle:
        "These are our services and prices. Not sure what you need? Message us and we'll advise you.",
      note: "Prices may vary depending on hair length and type. Not sure what you need? Just ask us, no commitment.",
      cta: "Book your appointment",
      groups: [
        { title: "Haircuts", items: [
          { name: "Kids' cut", desc: "Up to 8 years old", price: "10 €" },
          { name: "Men's cut", desc: "Scissor or clipper", price: "13 €" },
          { name: "Cut + wash", desc: "With wash and styling", price: "15 €" },
        ] },
        { title: "Cut & beard", items: [
          { name: "Beard (clipper)", desc: "Quick clipper tidy-up", price: "5 €" },
          { name: "Beard: shave or line-up", desc: "With a hot towel", price: "10 €" },
          { name: "Cut + beard", desc: "The most popular", price: "20 €", highlight: true },
          { name: "Cut + beard + wash", desc: "Wash included", price: "23 €" },
          { name: "Premium cut + beard", desc: "With colour, highlights or extras", price: "25 €" },
          { name: "Full package", desc: "Cut, beard, nose & ear wax, wash, facial cleanse and massage", price: "40 €" },
        ] },
        { title: "Colour, highlights & extras", items: [
          { name: "Beard colour", desc: "", price: "15 €" },
          { name: "Hair colour", desc: "", price: "20 €" },
          { name: "Highlights", desc: "", price: "25 €" },
          { name: "Highlights + colour", desc: "", price: "35 €" },
          { name: "Bleach + toner", desc: "", price: "30 €" },
          { name: "Double bleach + toner", desc: "", price: "40 €" },
          { name: "Nose & ear wax", desc: "", price: "5 €" },
          { name: "Wash", desc: "", price: "3 €" },
        ] },
      ],
    },
    booking: {
      eyebrow: "Book online",
      title: "Pick your time. Book instantly.",
      subtitle:
        "Choose a service, day and time. We'll text you a reminder an hour before your appointment.",
      serviceLabel: "Service",
      servicePlaceholder: "Choose a service",
      dayLabel: "Day",
      dayPlaceholder: "Choose a day",
      timeLabel: "Time",
      timePlaceholder: "Choose a time",
      unavailableMsg: "Online booking isn't available right now. Please try again later.",
      incompleteHint: "Choose a service, day and time to continue.",
      // Real (calendar-backed) booking flow
      nameLabel: "Your name",
      namePlaceholder: "First and last name",
      phoneLabel: "Phone",
      phonePlaceholder: "Your number",
      confirmBtn: "Book appointment",
      loadingSlots: "Finding open slots…",
      noSlots: "No slots left that day. Try another day.",
      successTitle: "Appointment booked!",
      successBody: "See you on {day} at {time}.",
      againBtn: "Book another appointment",
      takenMsg: "That slot was just taken. Please pick another time.",
      invalidPhoneMsg: "Please check your phone number, it doesn't look right.",
      errorMsg: "We couldn't complete the booking. Please try again.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Frequently asked questions.",
      subtitle:
        "Quick answers to what people ask us most. Can't find what you're looking for? Give us a call.",
      items: [
        { question: "Do I need an appointment or can I just walk in?", answer: "You're welcome to walk in, but to avoid waiting we recommend booking online. We confirm your time instantly and hold your slot." },
        { question: "How do I book an appointment?", answer: "The fastest way is booking online: pick a service, day and time, and we'll text you a reminder an hour ahead. You can also call us directly at +34 694 20 07 78." },
        { question: "How much is a haircut?", answer: "A men's cut is 13 € and the cut + beard package is 20 €. Kids' cuts are 10 €. You'll find the full list in the Prices section. The final price may vary with hair length." },
        { question: "Do you cut children's hair?", answer: "Yes. We do kids' cuts with plenty of patience and a friendly atmosphere, so it's easy and pleasant for the little ones too." },
        { question: "Do you do straight-razor shaves?", answer: "Yes. We offer the classic straight-razor shave with a hot towel: close, relaxing and with a perfect finish. A classic well worth trying." },
        { question: "What payment methods do you accept?", answer: "We accept both cash and card, whatever is most convenient for you." },
        { question: "Where are you and what are your hours?", answer: "We're in Los Abrigos, in the south of Tenerife, at Calle La Marina, Local 1 (38618). Hours are Monday to Friday 10:00–14:00 and 15:00–19:00, and Saturday 07:00–14:00. We're closed on Sundays." },
      ],
    },
    location: {
      eyebrow: "How to find us",
      title: "Come see us",
      subtitle: "We're in Tenerife, easy to find. Drop by or book ahead so you don't wait.",
      addressLabel: "Address",
      phoneLabel: "Phone",
      hoursLabel: "Opening hours",
      closed: "Closed",
      reserveBtn: "Book appointment",
      callBtn: "Call",
      mapsBtn: "Open in Google Maps",
    },
    contact: {
      eyebrow: "Book your appointment",
      title1: "Your next cut,",
      titleAccent: "one click away",
      subtitle:
        "Book your appointment online or call us directly. We confirm your slot instantly.",
      reserveBtn: "Book appointment",
      note: "We usually reply within a few minutes during opening hours",
    },
    footer: {
      tagline: "Barbershop in Tenerife. Cuts, beard and classic shave, with the care you deserve.",
      navTitle: "Navigation",
      contactTitle: "Contact",
      followTitle: "Follow us",
      rights: "All rights reserved.",
      privacy: "Privacy policy",
      legal: "Legal notice",
      nav: [
        { href: "#sobre", label: "About us" },
        { href: "#precios", label: "Prices" },
        { href: "#opiniones", label: "Reviews" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Location" },
        { href: "#contacto", label: "Contact" },
      ],
    },
    days: {
      Lunes: "Monday", Martes: "Tuesday", Miércoles: "Wednesday", Jueves: "Thursday",
      Viernes: "Friday", Sábado: "Saturday", Domingo: "Sunday",
    } as Record<string, string>,
  },

  fr: {
    nav: [
      { href: "#sobre", label: "À propos" },
      { href: "#especialidades", label: "Spécialités" },
      { href: "#precios", label: "Tarifs" },
      { href: "#reserva", label: "Réserver" },
      { href: "#por-que", label: "Pourquoi nous" },
      { href: "#opiniones", label: "Avis" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Accès" },
      { href: "#contacto", label: "Contact" },
    ],
    navReserve: "Réserver",
    hero: {
      badge: "Barbier · Tenerife",
      title1: "Entrez. Asseyez-vous.",
      title2: "Ressortez stylé.",
      subtitle1: "Barbier à Tenerife. Coupes, barbe et rasage classique,",
      subtitle2: "avec le soin que vous méritez.",
      ctaReserve: "Réserver",
      seePrices: "↓ Voir tous les tarifs",
      badges: ["Coupes et dégradés", "Réservation en ligne", "Apprécié par nos clients"],
    },
    video: {
      eyebrow: "Sur Instagram",
      title: "Voyez-nous à l'œuvre",
      subtitle:
        "Coupes, dégradés et barbe en vidéo. Jetez un œil à notre Instagram pour voir notre travail au quotidien.",
      hint: "@edustyle4 sur Instagram",
      cta: "Voir sur Instagram",
    },
    about: {
      eyebrow: "À propos de nous",
      title: "Ce n'est pas qu'une coupe. C'est votre image.",
      p1: "Chez Eduardo Style, chaque client est traité comme il le mérite : sans précipitation, en écoutant ce que vous recherchez et en soignant chaque détail. Coupes de cheveux, taille de barbe, rasage classique au coupe-chou et dessins personnalisés, le tout dans une ambiance conviviale et détendue.",
      p2: "Que vous veniez pour votre coupe habituelle ou pour changer complètement de style, nous vous conseillons ce qui vous va le mieux et le réalisons avec la technique et le soin que mérite votre image.",
      p3strong: "Réserver est simple : choisissez votre heure en ligne.",
      values: [
        { icon: "UserCog", title: "Savoir-faire", description: "Des années derrière le fauteuil. Chaque coupe, chaque barbe et chaque dégradé réalisés avec technique et précision." },
        { icon: "HeartHandshake", title: "Proximité", description: "Ici, vous n'êtes pas un numéro. Nous vous écoutons, comprenons votre style et vous conseillons ce qui vous va vraiment bien." },
        { icon: "Sparkles", title: "Le détail", description: "Serviette chaude, lignes nettes et finitions soignées. Vous repartez avec la sensation d'avoir été vraiment pris en charge." },
      ],
    },
    specialties: {
      eyebrow: "Nos spécialités",
      title: "Ce qu'on nous demande le plus à Tenerife",
      items: [
        { icon: "Wand2", title: "Taille et dessins de barbe à Tenerife", description: "Contour, taille au coupe-chou et à la tondeuse, et dessins de barbe adaptés à la forme de votre visage. L'un des services les plus demandés de la barbería." },
        { icon: "Waves", title: "Coiffures tendance homme à Tenerife", description: "Dégradés, coupes texturées et les styles du moment, adaptés à votre type de cheveux et à votre quotidien." },
        { icon: "Ruler", title: "Coupes de cheveux personnalisées à Tenerife", description: "Pas de coupe générique : on étudie la forme de votre visage et vos cheveux pour une coupe faite sur mesure." },
      ],
    },
    whyUs: {
      eyebrow: "Pourquoi Eduardo Style",
      title: "Quatre raisons de vous asseoir dans notre fauteuil",
      reasons: [
        { icon: "Scissors", title: "Des coupes sur mesure", description: "Dégradés, classiques, dessins et barbe travaillée. Nous adaptons chaque coupe à votre type de cheveux et à votre style." },
        { icon: "CalendarCheck", title: "Réservez sans appeler", description: "Demandez votre rendez-vous sur WhatsApp quand vous voulez, même en dehors des horaires. Confirmation en quelques minutes." },
        { icon: "Star", title: "Des clients fidèles", description: "La plupart de ceux qui essaient Eduardo Style reviennent. Bon accueil, bonne ambiance et un résultat qui se voit." },
        { icon: "MapPin", title: "À Tenerife, près de chez vous", description: "Facile à trouver, avec cette ambiance de barbier de quartier où l'on se sent comme à la maison." },
      ],
    },
    testimonials: {
      eyebrow: "Avis",
      title: "Ce que disent nos clients",
      badge: "Avis vérifiés Google",
      items: [
        { name: "Symka K.", rating: 5, text: "Waouh, je ne pouvais pas être plus satisfaite, Eduardo est un coiffeur PRO, je ressors avec un look de mannequin 😎", service: "Coupe de cheveux" },
        { name: "Luc H.", rating: 5, text: "Excellent service, sympathique et minutieux. Je recommande vivement cet endroit !", service: "Coupe de cheveux" },
        { name: "Idayra S.", rating: 5, text: "Eduardo est un vrai professionnel. Il a coupé les cheveux de mon fils de trois ans, qui déteste ça d'habitude, en lui parlant tout doucement — aucune larme. Vivement recommandé.", service: "Coupe enfant" },
        { name: "Fran O.", rating: 5, text: "Je n'ai jamais vu un salon aussi efficace. Les gars sont très sympas et travaillent super bien et vite. Je n'irais nulle part ailleurs, je les recommande sincèrement.", service: "Coupe de cheveux" },
        { name: "Jack", rating: 5, text: "Service excellent. Eduardo est très professionnel, attentif et minutieux. Il a parfaitement compris ce que je voulais, le résultat m'a beaucoup plu. Je reviendrai, c'est sûr.", service: "Coupe de cheveux" },
        { name: "Carl-Fredrik B.", rating: 5, text: "Il était temps de me couper les cheveux et d'arranger ma barbe, et juste en dehors du centre de Los Abrigos j'ai trouvé ce barbier talentueux et très abordable. Ils ont vraiment pris le temps, je me suis senti très bien pris en charge.", service: "Coupe + Barbe" },
      ],
    },
    prices: {
      eyebrow: "Tarifs",
      title: "Des prix clairs. Sans surprise.",
      subtitle:
        "Voici nos services et nos tarifs. Un doute sur ce dont vous avez besoin ? Écrivez-nous, on vous conseille.",
      note: "Les prix peuvent varier selon la longueur et le type de cheveux. Un doute ? Demandez-nous sans engagement.",
      cta: "Réserver votre rendez-vous",
      groups: [
        { title: "Coupes", items: [
          { name: "Coupe enfant", desc: "Jusqu'à 8 ans", price: "10 €" },
          { name: "Coupe homme", desc: "Aux ciseaux ou à la tondeuse", price: "13 €" },
          { name: "Coupe + shampoing", desc: "Avec shampoing et coiffage", price: "15 €" },
        ] },
        { title: "Coupe et barbe", items: [
          { name: "Barbe à la tondeuse", desc: "Entretien rapide", price: "5 €" },
          { name: "Barbe : rasage ou contour", desc: "Avec serviette chaude", price: "10 €" },
          { name: "Coupe + barbe", desc: "La plus demandée", price: "20 €", highlight: true },
          { name: "Coupe + barbe + shampoing", desc: "Shampoing inclus", price: "23 €" },
          { name: "Coupe + barbe premium", desc: "Avec couleur, mèches ou extras", price: "25 €" },
          { name: "Formule complète", desc: "Coupe, barbe, cire nez et oreilles, shampoing, nettoyage du visage et massage", price: "40 €" },
        ] },
        { title: "Couleur, mèches et extras", items: [
          { name: "Couleur de barbe", desc: "", price: "15 €" },
          { name: "Couleur de cheveux", desc: "", price: "20 €" },
          { name: "Mèches", desc: "", price: "25 €" },
          { name: "Mèches + couleur", desc: "", price: "35 €" },
          { name: "Décoloration + nuance", desc: "", price: "30 €" },
          { name: "Double décoloration + nuance", desc: "", price: "40 €" },
          { name: "Cire nez et oreilles", desc: "", price: "5 €" },
          { name: "Shampoing", desc: "", price: "3 €" },
        ] },
      ],
    },
    booking: {
      eyebrow: "Réservation en ligne",
      title: "Choisissez votre heure. Réservez à l'instant.",
      subtitle:
        "Choisissez un service, un jour et une heure. Nous vous enverrons un rappel par SMS une heure avant votre rendez-vous.",
      serviceLabel: "Service",
      servicePlaceholder: "Choisissez un service",
      dayLabel: "Jour",
      dayPlaceholder: "Choisissez un jour",
      timeLabel: "Heure",
      timePlaceholder: "Choisissez une heure",
      unavailableMsg: "La réservation en ligne n'est pas disponible pour le moment. Réessayez plus tard.",
      incompleteHint: "Choisissez un service, un jour et une heure pour continuer.",
      // Real (calendar-backed) booking flow
      nameLabel: "Votre nom",
      namePlaceholder: "Nom et prénom",
      phoneLabel: "Téléphone",
      phonePlaceholder: "Votre numéro",
      confirmBtn: "Réserver le rendez-vous",
      loadingSlots: "Recherche de créneaux…",
      noSlots: "Plus de créneaux ce jour-là. Essayez un autre jour.",
      successTitle: "Rendez-vous réservé !",
      successBody: "On vous attend le {day} à {time}.",
      againBtn: "Réserver un autre rendez-vous",
      takenMsg: "Ce créneau vient d'être pris. Choisissez une autre heure, s'il vous plaît.",
      invalidPhoneMsg: "Vérifiez votre numéro de téléphone, il ne semble pas correct.",
      errorMsg: "La réservation n'a pas pu aboutir. Veuillez réessayer.",
    },
    faq: {
      eyebrow: "Questions fréquentes",
      title: "Questions fréquentes. Réponses claires.",
      subtitle:
        "Réponses rapides aux questions les plus posées. Vous ne trouvez pas ce que vous cherchez ? Appelez-nous.",
      items: [
        { question: "Dois-je prendre rendez-vous ou puis-je venir directement ?", answer: "Vous pouvez venir sans rendez-vous, mais pour éviter l'attente nous vous recommandons de réserver en ligne. Nous confirmons l'heure à l'instant et vous gardons votre créneau." },
        { question: "Comment réserver un rendez-vous ?", answer: "Le plus rapide est de réserver en ligne : choisissez un service, un jour et une heure, et nous vous enverrons un rappel par SMS une heure avant. Vous pouvez aussi nous appeler directement au +34 694 20 07 78." },
        { question: "Combien coûte une coupe ?", answer: "Une coupe homme coûte 13 € et la formule coupe + barbe 20 €. Pour les enfants, 10 €. Retrouvez la liste complète dans la section Tarifs. Le prix final peut varier selon la longueur des cheveux." },
        { question: "Faites-vous les coupes pour enfants ?", answer: "Oui. Nous coupons les cheveux des enfants avec beaucoup de patience et de bonne humeur, pour que ce soit facile et agréable aussi pour les plus petits." },
        { question: "Faites-vous le rasage au coupe-chou ?", answer: "Oui. Nous proposons le rasage classique au coupe-chou avec serviette chaude : net, relaxant et avec une finition parfaite. Un classique qui vaut vraiment le détour." },
        { question: "Quels moyens de paiement acceptez-vous ?", answer: "Nous acceptons les paiements en espèces et par carte, selon ce qui vous arrange le mieux." },
        { question: "Où êtes-vous situés et quels sont vos horaires ?", answer: "Nous sommes à Los Abrigos, dans le sud de Tenerife, Calle La Marina, Local 1 (38618). Horaires : du lundi au vendredi de 10h00 à 14h00 et de 15h00 à 19h00, et le samedi de 07h00 à 14h00. Fermé le dimanche." },
      ],
    },
    location: {
      eyebrow: "Comment venir",
      title: "Venez nous voir",
      subtitle: "Nous sommes à Tenerife, facile à trouver. Passez nous voir ou réservez à l'avance pour ne pas attendre.",
      addressLabel: "Adresse",
      phoneLabel: "Téléphone",
      hoursLabel: "Horaires",
      closed: "Fermé",
      reserveBtn: "Réserver",
      callBtn: "Appeler",
      mapsBtn: "Ouvrir dans Google Maps",
    },
    contact: {
      eyebrow: "Réservez votre rendez-vous",
      title1: "Votre prochaine coupe,",
      titleAccent: "à un clic près",
      subtitle:
        "Réservez votre rendez-vous en ligne ou appelez-nous directement. Nous confirmons votre créneau à l'instant.",
      reserveBtn: "Réserver",
      note: "Nous répondons généralement en quelques minutes pendant les horaires d'ouverture",
    },
    footer: {
      tagline: "Barbier à Tenerife. Coupes, barbe et rasage classique, avec le soin que vous méritez.",
      navTitle: "Navigation",
      contactTitle: "Contact",
      followTitle: "Suivez-nous",
      rights: "Tous droits réservés.",
      privacy: "Politique de confidentialité",
      legal: "Mentions légales",
      nav: [
        { href: "#sobre", label: "À propos" },
        { href: "#precios", label: "Tarifs" },
        { href: "#opiniones", label: "Avis" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Accès" },
        { href: "#contacto", label: "Contact" },
      ],
    },
    days: {
      Lunes: "Lundi", Martes: "Mardi", Miércoles: "Mercredi", Jueves: "Jeudi",
      Viernes: "Vendredi", Sábado: "Samedi", Domingo: "Dimanche",
    } as Record<string, string>,
  },

  de: {
    nav: [
      { href: "#sobre", label: "Über uns" },
      { href: "#especialidades", label: "Spezialgebiete" },
      { href: "#precios", label: "Preise" },
      { href: "#reserva", label: "Termin buchen" },
      { href: "#por-que", label: "Warum wir" },
      { href: "#opiniones", label: "Bewertungen" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Anfahrt" },
      { href: "#contacto", label: "Kontakt" },
    ],
    navReserve: "Termin buchen",
    hero: {
      badge: "Barbershop · Teneriffa",
      title1: "Reinkommen. Platz nehmen.",
      title2: "Gestylt rausgehen.",
      subtitle1: "Barbershop auf Teneriffa. Haarschnitt, Bart und klassische Rasur,",
      subtitle2: "mit der Sorgfalt, die Sie verdienen.",
      ctaReserve: "Jetzt buchen",
      seePrices: "↓ Alle Preise ansehen",
      badges: ["Schnitte & Fades", "Online buchen", "Von Kunden geschätzt"],
    },
    video: {
      eyebrow: "Auf Instagram",
      title: "Sehen Sie uns bei der Arbeit",
      subtitle:
        "Schnitte, Fades und Bartpflege im Video. Schauen Sie auf unserem Instagram vorbei und sehen Sie, wie wir arbeiten.",
      hint: "@edustyle4 auf Instagram",
      cta: "Auf Instagram ansehen",
    },
    about: {
      eyebrow: "Über uns",
      title: "Es ist nicht nur ein Haarschnitt. Es ist Ihr Look.",
      p1: "Bei Eduardo Style wird jeder Kunde so behandelt, wie er es verdient: ohne Eile, mit einem offenen Ohr für Ihre Wünsche und mit Liebe zum Detail. Haarschnitte, Bartpflege, klassische Rasur mit dem Rasiermesser und individuelle Designs, alles in entspannter, familiärer Atmosphäre.",
      p2: "Ob Sie für Ihren gewohnten Schnitt kommen oder komplett neu aussehen möchten: Wir beraten Sie, was am besten zu Ihnen passt, und setzen es mit der Technik und Sorgfalt um, die Ihr Look verdient.",
      p3strong: "Buchen ist einfach: Zeit online wählen, fertig.",
      values: [
        { icon: "UserCog", title: "Handwerk", description: "Jahrelange Erfahrung auf dem Stuhl. Jeder Schnitt, jeder Bart und jeder Fade mit Technik und ruhiger Hand." },
        { icon: "HeartHandshake", title: "Nähe", description: "Hier sind Sie keine Nummer. Wir hören zu, verstehen Ihren Stil und beraten Sie ehrlich, was wirklich zu Ihnen passt." },
        { icon: "Sparkles", title: "Liebe zum Detail", description: "Warmes Handtuch, saubere Linien und sorgfältige Finishes. Sie gehen mit dem Gefühl, wirklich umsorgt worden zu sein." },
      ],
    },
    specialties: {
      eyebrow: "Unsere Spezialgebiete",
      title: "Das wird bei uns auf Teneriffa am häufigsten gefragt",
      items: [
        { icon: "Wand2", title: "Bartpflege und Bartdesign auf Teneriffa", description: "Konturenschnitt, Rasiermesser und Maschine, sowie Bartdesigns passend zu Ihrer Gesichtsform. Einer der meistgefragten Services im Barbershop." },
        { icon: "Waves", title: "Angesagte Herrenfrisuren auf Teneriffa", description: "Fades, texturierte Schnitte und die Styles, die gerade angesagt sind, angepasst an Ihren Haartyp und Alltag." },
        { icon: "Ruler", title: "Individuelle Haarschnitte auf Teneriffa", description: "Kein Schnitt von der Stange: Wir analysieren Ihre Gesichtsform und Ihr Haar für einen Schnitt, der wirklich zu Ihnen passt." },
      ],
    },
    whyUs: {
      eyebrow: "Warum Eduardo Style",
      title: "Vier Gründe, bei uns Platz zu nehmen",
      reasons: [
        { icon: "Scissors", title: "Schnitte nach Maß", description: "Fades, Klassiker, Designs und ausgearbeiteter Bart. Wir passen jeden Schnitt an Ihren Haartyp und Stil an." },
        { icon: "CalendarCheck", title: "Buchen ohne Anruf", description: "Fordern Sie Ihren Termin jederzeit per WhatsApp an, auch außerhalb der Öffnungszeiten. Bestätigung in wenigen Minuten." },
        { icon: "Star", title: "Kunden, die wiederkommen", description: "Die meisten, die Eduardo Style ausprobieren, kommen wieder. Guter Service, gute Atmosphäre und ein Ergebnis, das man sieht." },
        { icon: "MapPin", title: "Direkt hier auf Teneriffa", description: "Leicht zu finden, mit dem Gefühl eines Barbershops von nebenan, in dem man sich wie zuhause fühlt." },
      ],
    },
    testimonials: {
      eyebrow: "Bewertungen",
      title: "Was unsere Kunden sagen",
      badge: "Verifizierte Google-Bewertungen",
      items: [
        { name: "Symka K.", rating: 5, text: "Wow, ich könnte nicht zufriedener sein — Eduardo ist ein Profi-Friseur, ich sehe jetzt aus wie ein Model 😎", service: "Haarschnitt" },
        { name: "Luc H.", rating: 5, text: "Toller Service, freundlich und gründlich. Kann ich nur empfehlen!", service: "Haarschnitt" },
        { name: "Idayra S.", rating: 5, text: "Eduardo ist ein fantastischer Profi. Er hat meinem dreijährigen Sohn die Haare geschnitten — der Haareschneiden sonst hasst — und ihn dabei so sanft beruhigt, dass er überhaupt nicht gelitten hat. Sehr empfehlenswert.", service: "Kinderhaarschnitt" },
        { name: "Fran O.", rating: 5, text: "Ich war noch nie in einem effizienteren Barbershop. Die Jungs sind sehr freundlich und arbeiten unglaublich gut und schnell. Ich würde nirgendwo anders hingehen.", service: "Haarschnitt" },
        { name: "Jack", rating: 5, text: "Ausgezeichneter Service. Eduardo ist sehr professionell, aufmerksam und detailverliebt. Er hat genau verstanden, was ich wollte, und das Ergebnis war toll. Ich komme definitiv wieder.", service: "Haarschnitt" },
        { name: "Carl-Fredrik B.", rating: 5, text: "Es war Zeit für einen Haarschnitt und meinen Bart in Form zu bringen, und gleich außerhalb des Zentrums von Los Abrigos fand ich diesen talentierten und sehr erschwinglichen Barbier. Sie haben sich wirklich Zeit genommen, ich fühlte mich bestens umsorgt.", service: "Schnitt + Bart" },
      ],
    },
    prices: {
      eyebrow: "Preise",
      title: "Klare Preise. Keine Überraschungen.",
      subtitle:
        "Das sind unsere Leistungen und Preise. Nicht sicher, was Sie brauchen? Schreiben Sie uns, wir beraten Sie.",
      note: "Die Preise können je nach Haarlänge und -typ variieren. Unsicher? Fragen Sie uns einfach, ganz unverbindlich.",
      cta: "Termin buchen",
      groups: [
        { title: "Haarschnitte", items: [
          { name: "Kinderhaarschnitt", desc: "Bis 8 Jahre", price: "10 €" },
          { name: "Herrenhaarschnitt", desc: "Mit Schere oder Maschine", price: "13 €" },
          { name: "Schnitt + Waschen", desc: "Mit Waschen und Styling", price: "15 €" },
        ] },
        { title: "Schnitt & Bart", items: [
          { name: "Bart mit Maschine", desc: "Schnelle Auffrischung", price: "5 €" },
          { name: "Bart: Rasur oder Konturen", desc: "Mit warmem Handtuch", price: "10 €" },
          { name: "Schnitt + Bart", desc: "Am meisten gebucht", price: "20 €", highlight: true },
          { name: "Schnitt + Bart + Waschen", desc: "Inklusive Waschen", price: "23 €" },
          { name: "Premium Schnitt + Bart", desc: "Mit Farbe, Strähnen oder Extras", price: "25 €" },
          { name: "Komplettpaket", desc: "Schnitt, Bart, Nasen- und Ohrenwachs, Waschen, Gesichtsreinigung und Massage", price: "40 €" },
        ] },
        { title: "Farbe, Strähnen & Extras", items: [
          { name: "Bartfarbe", desc: "", price: "15 €" },
          { name: "Haarfarbe", desc: "", price: "20 €" },
          { name: "Strähnen", desc: "", price: "25 €" },
          { name: "Strähnen + Farbe", desc: "", price: "35 €" },
          { name: "Blondierung + Tönung", desc: "", price: "30 €" },
          { name: "Doppelte Blondierung + Tönung", desc: "", price: "40 €" },
          { name: "Nasen- und Ohrenwachs", desc: "", price: "5 €" },
          { name: "Waschen", desc: "", price: "3 €" },
        ] },
      ],
    },
    booking: {
      eyebrow: "Online buchen",
      title: "Zeit wählen. Sofort buchen.",
      subtitle:
        "Wählen Sie Leistung, Tag und Uhrzeit. Eine Stunde vor Ihrem Termin erhalten Sie eine SMS-Erinnerung.",
      serviceLabel: "Leistung",
      servicePlaceholder: "Leistung wählen",
      dayLabel: "Tag",
      dayPlaceholder: "Tag wählen",
      timeLabel: "Uhrzeit",
      timePlaceholder: "Uhrzeit wählen",
      unavailableMsg: "Die Online-Buchung ist gerade nicht verfügbar. Bitte versuchen Sie es später erneut.",
      incompleteHint: "Wählen Sie Leistung, Tag und Uhrzeit, um fortzufahren.",
      // Real (calendar-backed) booking flow
      nameLabel: "Dein Name",
      namePlaceholder: "Vor- und Nachname",
      phoneLabel: "Telefon",
      phonePlaceholder: "Deine Nummer",
      confirmBtn: "Termin buchen",
      loadingSlots: "Freie Zeiten werden gesucht…",
      noSlots: "An dem Tag sind keine Zeiten mehr frei. Probier einen anderen Tag.",
      successTitle: "Termin gebucht!",
      successBody: "Wir sehen uns am {day} um {time}.",
      againBtn: "Weiteren Termin buchen",
      takenMsg: "Diese Zeit wurde gerade vergeben. Bitte wähl eine andere Uhrzeit.",
      invalidPhoneMsg: "Bitte überprüfe deine Telefonnummer, sie scheint nicht korrekt zu sein.",
      errorMsg: "Die Buchung hat nicht geklappt. Bitte versuch es erneut.",
    },
    faq: {
      eyebrow: "Häufige Fragen",
      title: "Häufige Fragen. Klare Antworten.",
      subtitle:
        "Schnelle Antworten auf die häufigsten Fragen. Nicht gefunden, was Sie suchen? Rufen Sie uns an.",
      items: [
        { question: "Brauche ich einen Termin oder kann ich einfach vorbeikommen?", answer: "Sie können gerne ohne Termin vorbeikommen, aber um Wartezeit zu vermeiden, empfehlen wir eine Online-Buchung. Wir bestätigen Ihre Zeit sofort und reservieren Ihren Platz." },
        { question: "Wie buche ich einen Termin?", answer: "Am schnellsten geht es online: Leistung, Tag und Uhrzeit wählen, und Sie erhalten eine Stunde vorher eine SMS-Erinnerung. Sie können uns auch direkt unter +34 694 20 07 78 anrufen." },
        { question: "Was kostet ein Haarschnitt?", answer: "Ein Herrenhaarschnitt kostet 13 € und das Paket Schnitt + Bart 20 €. Für Kinder 10 €. Die vollständige Liste finden Sie im Bereich Preise. Der Endpreis kann je nach Haarlänge variieren." },
        { question: "Schneiden Sie auch Kinderhaare?", answer: "Ja. Wir schneiden Kinderhaare mit viel Geduld und guter Atmosphäre, damit es auch für die Kleinsten einfach und angenehm ist." },
        { question: "Bieten Sie Rasur mit dem Rasiermesser an?", answer: "Ja. Wir bieten die klassische Rasur mit dem Rasiermesser und warmem Handtuch: gründlich, entspannend und mit perfektem Finish. Ein Klassiker, den man ausprobiert haben sollte." },
        { question: "Welche Zahlungsmethoden akzeptieren Sie?", answer: "Wir akzeptieren Barzahlung und Kartenzahlung, ganz wie es Ihnen am liebsten ist." },
        { question: "Wo befindet ihr euch und welche Öffnungszeiten habt ihr?", answer: "Wir befinden uns in Los Abrigos, im Süden von Teneriffa, Calle La Marina, Local 1 (38618). Öffnungszeiten: Montag bis Freitag 10:00–14:00 und 15:00–19:00 Uhr, Samstag 07:00–14:00 Uhr. Sonntags geschlossen." },
      ],
    },
    location: {
      eyebrow: "Anfahrt",
      title: "Besuchen Sie uns",
      subtitle: "Wir sind auf Teneriffa, leicht zu finden. Kommen Sie vorbei oder buchen Sie vorab, damit Sie nicht warten müssen.",
      addressLabel: "Adresse",
      phoneLabel: "Telefon",
      hoursLabel: "Öffnungszeiten",
      closed: "Geschlossen",
      reserveBtn: "Termin buchen",
      callBtn: "Anrufen",
      mapsBtn: "In Google Maps öffnen",
    },
    contact: {
      eyebrow: "Termin buchen",
      title1: "Ihr nächster Schnitt,",
      titleAccent: "nur einen Klick entfernt",
      subtitle:
        "Buchen Sie Ihren Termin online oder rufen Sie uns direkt an. Wir bestätigen Ihren Platz sofort.",
      reserveBtn: "Termin buchen",
      note: "Wir antworten während der Öffnungszeiten meist innerhalb weniger Minuten",
    },
    footer: {
      tagline: "Barbershop auf Teneriffa. Haarschnitt, Bart und klassische Rasur, mit der Sorgfalt, die Sie verdienen.",
      navTitle: "Navigation",
      contactTitle: "Kontakt",
      followTitle: "Folgen Sie uns",
      rights: "Alle Rechte vorbehalten.",
      privacy: "Datenschutzerklärung",
      legal: "Impressum",
      nav: [
        { href: "#sobre", label: "Über uns" },
        { href: "#precios", label: "Preise" },
        { href: "#opiniones", label: "Bewertungen" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Anfahrt" },
        { href: "#contacto", label: "Kontakt" },
      ],
    },
    days: {
      Lunes: "Montag", Martes: "Dienstag", Miércoles: "Mittwoch", Jueves: "Donnerstag",
      Viernes: "Freitag", Sábado: "Samstag", Domingo: "Sonntag",
    } as Record<string, string>,
  },
} as const;

export function getContent(lang: Lang) {
  return content[lang];
}
