// Bilingual content dictionary (ES default, EN for the expat/tourist clientele).
// Every visible string lives here so components stay language-agnostic.
// Prices and phone numbers are language-independent and stay in business.ts / here as-is.

export type Lang = "es" | "en" | "fr" | "de";

export const LANG_PATHS: Record<Lang, string> = {
  es: "/",
  en: "/en",
  fr: "/fr",
  de: "/de",
};

export const LANG_LABELS: Record<Lang, string> = {
  es: "ES",
  en: "EN",
  fr: "FR",
  de: "DE",
};

export const content = {
  es: {
    nav: [
      { href: "#sobre", label: "Sobre" },
      { href: "#precios", label: "Precios" },
      { href: "#por-que", label: "Por qué" },
      { href: "#opiniones", label: "Opiniones" },
      { href: "#preguntas", label: "Preguntas" },
      { href: "#ubicacion", label: "Ubicación" },
      { href: "#contacto", label: "Contacto" },
    ],
    navReserve: "Reservar",
    navReserveMobile: "Reservar por WhatsApp",
    floatingWhatsappLabel: "Escríbenos por WhatsApp",
    hero: {
      badge: "Barbería · Tenerife",
      title1: "Entra. Siéntate.",
      title2: "Sal con estilo.",
      subtitle1: "Barbería en Tenerife. Cortes, barba y afeitado clásico,",
      subtitle2: "con la atención que te mereces.",
      ctaReserve: "Reservar cita",
      ctaWhatsApp: "Reserva por WhatsApp",
      seePrices: "↓ Ver todos los precios",
      badges: ["Cortes y degradados", "Reserva por WhatsApp", "Valorado por sus clientes"],
    },
    video: {
      eyebrow: "En Instagram",
      title: "Míranos en acción",
      subtitle:
        "Cortes, degradados y barba en vídeo. Echa un vistazo a nuestro Instagram y mira cómo trabajamos en el día a día.",
      hint: "@edustyle4 en Instagram",
      cta: "Ver en Instagram",
    },
    about: {
      eyebrow: "Sobre nosotros",
      title: "No es solo un corte. Es tu imagen.",
      p1: "En Eduardo Style tratamos cada cliente como se merece: sin prisas, escuchando lo que buscas y cuidando cada detalle. Cortes de pelo, arreglo de barba, afeitado clásico a navaja y diseños personalizados, todo en un ambiente cercano y relajado.",
      p2: "Da igual si vienes a por tu corte de siempre o quieres cambiar de look por completo: te aconsejamos lo que mejor te queda y lo hacemos con la técnica y el mimo que se merece tu imagen.",
      p3strong: "Reservar es fácil: un mensaje de WhatsApp y listo.",
      values: [
        { icon: "UserCog", title: "Oficio", description: "Años detrás de la silla. Cada corte, cada barba y cada degradado hecho con técnica y buen pulso." },
        { icon: "HeartHandshake", title: "Cercanía", description: "Aquí no eres un número. Te escuchamos, entendemos tu estilo y te aconsejamos lo que de verdad te queda bien." },
        { icon: "Sparkles", title: "Detalle", description: "Toalla caliente, líneas limpias y acabados cuidados. Sales con la sensación de haberte cuidado de verdad." },
      ],
    },
    whyUs: {
      eyebrow: "Por qué Eduardo Style",
      title: "Cuatro razones para sentarte en nuestra silla",
      reasons: [
        { icon: "Scissors", title: "Cortes a tu medida", description: "Degradados, clásicos, diseños y barba trabajada. Adaptamos cada corte a tu tipo de pelo y a tu estilo." },
        { icon: "CalendarCheck", title: "Reserva sin llamadas", description: "Pide tu cita por WhatsApp cuando quieras, incluso fuera del horario. Te confirmamos en minutos." },
        { icon: "Star", title: "Clientes que repiten", description: "La mayoría de quienes prueban Eduardo Style vuelven. Buen trato, buen ambiente y un acabado que se nota." },
        { icon: "MapPin", title: "En tu zona, en Tenerife", description: "Fácil de encontrar y con ese trato de barbería de barrio en el que te sientes como en casa." },
      ],
    },
    testimonials: {
      eyebrow: "Opiniones",
      title: "Lo que dicen nuestros clientes",
      badge: "Reseñas verificadas de Google",
      items: [
        { name: "Carlos M.", rating: 5, text: "El mejor barbero de la zona. Salgo siempre con el corte perfecto y la barba impecable. Trato de 10 y muy buen ambiente.", service: "Corte + Barba" },
        { name: "Javi R.", rating: 5, text: "Llevo meses viniendo y no lo cambio. Buen degradado, sin esperas si reservas por WhatsApp y siempre con buen rollo.", service: "Degradado" },
        { name: "Airam G.", rating: 5, text: "El afeitado a navaja con toalla caliente es otro nivel. Sales como nuevo. Muy recomendable, se nota el oficio.", service: "Afeitado a navaja" },
        { name: "Dani P.", rating: 5, text: "Profesional y cercano. Te aconseja lo que te queda bien de verdad, no solo lo que pides. Repito seguro.", service: "Corte de pelo" },
        { name: "Miguel Á.", rating: 5, text: "Llevo a mi hijo y tiene una paciencia enorme con los peques. Corte genial y sin dramas. De diez.", service: "Corte niño" },
        { name: "Rubén S.", rating: 5, text: "Calidad, buen precio y buen rollo. Se nota que le gusta lo que hace. Se ha convertido en mi barbería fija.", service: "Corte + Barba" },
      ],
    },
    prices: {
      eyebrow: "Precios",
      title: "Tarifas claras. Sin sorpresas.",
      subtitle:
        "Estos son nuestros servicios y precios. ¿Dudas sobre lo que necesitas? Escríbenos y te asesoramos.",
      note: "Los precios pueden variar según el largo y el tipo de pelo. ¿Dudas sobre lo que necesitas? Pregúntanos sin compromiso.",
      cta: "Reserva tu cita por WhatsApp",
      groups: [
        { title: "Cortes", items: [
          { name: "Corte de niño", desc: "Hasta 8 años", price: "10 €" },
          { name: "Corte de caballero", desc: "A tijera o máquina", price: "13 €" },
          { name: "Corte + lavado", desc: "Con lavado y peinado", price: "15 €" },
        ] },
        { title: "Corte y barba", items: [
          { name: "Barba a máquina", desc: "Repaso rápido", price: "5 €" },
          { name: "Barba: afeitado o perfilado", desc: "Con toalla caliente", price: "10 €" },
          { name: "Corte + barba", desc: "El más pedido", price: "20 €", highlight: true },
          { name: "Corte + barba + lavado", desc: "Con lavado incluido", price: "23 €" },
          { name: "Corte + barba premium", desc: "Con color, mechas o extras", price: "25 €" },
          { name: "Pack completo", desc: "Corte, barba, cera nariz y orejas, lavado, limpieza facial y masaje", price: "40 €" },
        ] },
        { title: "Color, mechas y extras", items: [
          { name: "Color de barba", desc: "", price: "15 €" },
          { name: "Color de cabello", desc: "", price: "20 €" },
          { name: "Mechas", desc: "", price: "25 €" },
          { name: "Mechas + color", desc: "", price: "35 €" },
          { name: "Decoloración + matiz", desc: "", price: "30 €" },
          { name: "Doble decoloración + matiz", desc: "", price: "40 €" },
          { name: "Cera nariz y orejas", desc: "", price: "5 €" },
          { name: "Lavado", desc: "", price: "3 €" },
        ] },
      ],
    },
    faq: {
      eyebrow: "Preguntas frecuentes",
      title: "Preguntas frecuentes. Respuestas claras.",
      subtitle:
        "Respuestas rápidas a lo que más nos preguntan. ¿No encuentras lo que buscas? Escríbenos por WhatsApp.",
      items: [
        { question: "¿Necesito pedir cita o puedo ir directamente?", answer: "Puedes pasarte sin cita, pero para no esperar te recomendamos reservar por WhatsApp. Te confirmamos la hora en minutos y te guardamos el hueco." },
        { question: "¿Cómo reservo una cita?", answer: "Lo más rápido es por WhatsApp al +34 694 20 07 78. También puedes llamarnos directamente. Solemos responder en pocos minutos durante el horario de apertura." },
        { question: "¿Cuánto cuesta un corte?", answer: "Un corte de caballero cuesta 13 € y el pack corte + barba 20 €. Los niños 10 €. Tienes la lista completa en la sección de Precios. El precio final puede variar según el largo del pelo." },
        { question: "¿Cortáis a niños?", answer: "Sí. Hacemos cortes para niños con mucha paciencia y buen ambiente, para que la experiencia sea fácil y agradable también para los más pequeños." },
        { question: "¿Hacéis afeitado a navaja?", answer: "Sí. Ofrecemos el afeitado clásico a navaja con toalla caliente: apurado, relajante y con un acabado perfecto. Todo un clásico que merece la pena probar." },
        { question: "¿Qué formas de pago aceptáis?", answer: "Aceptamos pago en efectivo y con tarjeta, lo que te resulte más cómodo." },
        { question: "¿Dónde estáis y qué horario tenéis?", answer: "Estamos en Los Abrigos, en el sur de Tenerife, en la Calle La Marina, Local 1 (38618). El horario es de Lunes a Viernes de 10:00 a 19:00 y Sábados de 10:00 a 16:00. Los Domingos permanecemos cerrados." },
      ],
    },
    location: {
      eyebrow: "Cómo llegar",
      title: "Ven a vernos",
      subtitle: "Estamos en Tenerife, fácil de encontrar. Pásate o reserva antes tu cita para no esperar.",
      addressLabel: "Dirección",
      phoneLabel: "Teléfono",
      hoursLabel: "Horario",
      closed: "Cerrado",
      whatsappBtn: "WhatsApp",
      callBtn: "Llamar",
      mapsBtn: "Abrir en Google Maps",
    },
    contact: {
      eyebrow: "Reserva tu cita",
      title1: "Tu próximo corte,",
      titleAccent: "a un mensaje",
      subtitle:
        "Escríbenos por WhatsApp o llámanos directamente. Te confirmamos la cita en minutos y te reservamos tu hueco.",
      whatsappBtn: "Reserva por WhatsApp",
      note: "Solemos responder en pocos minutos durante el horario de apertura",
    },
    footer: {
      tagline: "Barbería en Tenerife. Cortes, barba y afeitado clásico, con la atención que te mereces.",
      navTitle: "Navegación",
      contactTitle: "Contacto",
      followTitle: "Síguenos",
      rights: "Todos los derechos reservados.",
      privacy: "Política de privacidad",
      legal: "Aviso legal",
      nav: [
        { href: "#sobre", label: "Sobre nosotros" },
        { href: "#precios", label: "Precios" },
        { href: "#opiniones", label: "Opiniones" },
        { href: "#preguntas", label: "Preguntas" },
        { href: "#ubicacion", label: "Ubicación" },
        { href: "#contacto", label: "Contacto" },
      ],
    },
    days: {
      Lunes: "Lunes", Martes: "Martes", Miércoles: "Miércoles", Jueves: "Jueves",
      Viernes: "Viernes", Sábado: "Sábado", Domingo: "Domingo",
    } as Record<string, string>,
  },

  en: {
    nav: [
      { href: "#sobre", label: "About" },
      { href: "#precios", label: "Prices" },
      { href: "#por-que", label: "Why us" },
      { href: "#opiniones", label: "Reviews" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Location" },
      { href: "#contacto", label: "Contact" },
    ],
    navReserve: "Book",
    navReserveMobile: "Book on WhatsApp",
    floatingWhatsappLabel: "Message us on WhatsApp",
    hero: {
      badge: "Barbershop · Tenerife",
      title1: "Walk in. Sit down.",
      title2: "Walk out sharp.",
      subtitle1: "Barbershop in Tenerife. Cuts, beard and classic shave,",
      subtitle2: "with the care you deserve.",
      ctaReserve: "Book now",
      ctaWhatsApp: "Book on WhatsApp",
      seePrices: "↓ See all prices",
      badges: ["Cuts & fades", "Book on WhatsApp", "Loved by customers"],
    },
    video: {
      eyebrow: "On Instagram",
      title: "See us in action",
      subtitle:
        "Cuts, fades and beard work on video. Take a look at our Instagram and see how we work day to day.",
      hint: "@edustyle4 on Instagram",
      cta: "View on Instagram",
    },
    about: {
      eyebrow: "About us",
      title: "It's not just a haircut. It's your look.",
      p1: "At Eduardo Style we treat every client the way they deserve: no rush, listening to what you want and taking care of every detail. Haircuts, beard trims, classic straight-razor shaves and custom designs, all in a friendly, relaxed atmosphere.",
      p2: "Whether you come for your usual cut or want a complete change of look, we advise you on what suits you best and do it with the skill and care your image deserves.",
      p3strong: "Booking is easy: one WhatsApp message and you're done.",
      values: [
        { icon: "UserCog", title: "Craft", description: "Years behind the chair. Every cut, beard and fade done with technique and a steady hand." },
        { icon: "HeartHandshake", title: "Personal", description: "Here you're not a number. We listen, understand your style and advise you on what really suits you." },
        { icon: "Sparkles", title: "Detail", description: "Hot towel, clean lines and careful finishes. You leave feeling genuinely looked after." },
      ],
    },
    whyUs: {
      eyebrow: "Why Eduardo Style",
      title: "Four reasons to sit in our chair",
      reasons: [
        { icon: "Scissors", title: "Cuts made for you", description: "Fades, classics, designs and worked beards. We adapt every cut to your hair type and style." },
        { icon: "CalendarCheck", title: "Book without calling", description: "Request your appointment on WhatsApp whenever you like, even after hours. We confirm within minutes." },
        { icon: "Star", title: "Clients who come back", description: "Most people who try Eduardo Style return. Great service, great atmosphere and a finish you can see." },
        { icon: "MapPin", title: "Right here in Tenerife", description: "Easy to find, with that neighbourhood-barbershop feel where you're right at home." },
      ],
    },
    testimonials: {
      eyebrow: "Reviews",
      title: "What our clients say",
      badge: "Verified Google reviews",
      items: [
        { name: "Carlos M.", rating: 5, text: "The best barber around. I always leave with the perfect cut and a flawless beard. Top service and a great vibe.", service: "Cut + Beard" },
        { name: "Javi R.", rating: 5, text: "I've been coming for months and won't change. Great fade, no waiting if you book on WhatsApp, always good vibes.", service: "Fade" },
        { name: "Airam G.", rating: 5, text: "The straight-razor shave with a hot towel is another level. You leave feeling brand new. Highly recommended.", service: "Straight-razor shave" },
        { name: "Dani P.", rating: 5, text: "Professional and friendly. He advises what actually suits you, not just what you ask for. Definitely coming back.", service: "Haircut" },
        { name: "Miguel Á.", rating: 5, text: "I bring my son and he has huge patience with the little ones. Great cut and no drama. Ten out of ten.", service: "Kids' cut" },
        { name: "Rubén S.", rating: 5, text: "Quality, good price and good vibes. You can tell he loves what he does. Now my go-to barbershop.", service: "Cut + Beard" },
      ],
    },
    prices: {
      eyebrow: "Prices",
      title: "Clear prices. No surprises.",
      subtitle:
        "These are our services and prices. Not sure what you need? Message us and we'll advise you.",
      note: "Prices may vary depending on hair length and type. Not sure what you need? Just ask us, no commitment.",
      cta: "Book your appointment on WhatsApp",
      groups: [
        { title: "Haircuts", items: [
          { name: "Kids' cut", desc: "Up to 8 years old", price: "10 €" },
          { name: "Men's cut", desc: "Scissor or clipper", price: "13 €" },
          { name: "Cut + wash", desc: "With wash and styling", price: "15 €" },
        ] },
        { title: "Cut & beard", items: [
          { name: "Beard (clipper)", desc: "Quick clipper tidy-up", price: "5 €" },
          { name: "Beard: shave or line-up", desc: "With a hot towel", price: "10 €" },
          { name: "Cut + beard", desc: "The most popular", price: "20 €", highlight: true },
          { name: "Cut + beard + wash", desc: "Wash included", price: "23 €" },
          { name: "Premium cut + beard", desc: "With colour, highlights or extras", price: "25 €" },
          { name: "Full package", desc: "Cut, beard, nose & ear wax, wash, facial cleanse and massage", price: "40 €" },
        ] },
        { title: "Colour, highlights & extras", items: [
          { name: "Beard colour", desc: "", price: "15 €" },
          { name: "Hair colour", desc: "", price: "20 €" },
          { name: "Highlights", desc: "", price: "25 €" },
          { name: "Highlights + colour", desc: "", price: "35 €" },
          { name: "Bleach + toner", desc: "", price: "30 €" },
          { name: "Double bleach + toner", desc: "", price: "40 €" },
          { name: "Nose & ear wax", desc: "", price: "5 €" },
          { name: "Wash", desc: "", price: "3 €" },
        ] },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Frequently asked questions.",
      subtitle:
        "Quick answers to what people ask us most. Can't find what you're looking for? Message us on WhatsApp.",
      items: [
        { question: "Do I need an appointment or can I just walk in?", answer: "You're welcome to walk in, but to avoid waiting we recommend booking on WhatsApp. We confirm your time within minutes and hold your slot." },
        { question: "How do I book an appointment?", answer: "The fastest way is WhatsApp at +34 694 20 07 78. You can also call us directly. We usually reply within a few minutes during opening hours." },
        { question: "How much is a haircut?", answer: "A men's cut is 13 € and the cut + beard package is 20 €. Kids' cuts are 10 €. You'll find the full list in the Prices section. The final price may vary with hair length." },
        { question: "Do you cut children's hair?", answer: "Yes. We do kids' cuts with plenty of patience and a friendly atmosphere, so it's easy and pleasant for the little ones too." },
        { question: "Do you do straight-razor shaves?", answer: "Yes. We offer the classic straight-razor shave with a hot towel: close, relaxing and with a perfect finish. A classic well worth trying." },
        { question: "What payment methods do you accept?", answer: "We accept both cash and card, whatever is most convenient for you." },
        { question: "Where are you and what are your hours?", answer: "We're in Los Abrigos, in the south of Tenerife, at Calle La Marina, Local 1 (38618). Hours are Monday to Friday 10:00–19:00 and Saturday 10:00–16:00. We're closed on Sundays." },
      ],
    },
    location: {
      eyebrow: "How to find us",
      title: "Come see us",
      subtitle: "We're in Tenerife, easy to find. Drop by or book ahead so you don't wait.",
      addressLabel: "Address",
      phoneLabel: "Phone",
      hoursLabel: "Opening hours",
      closed: "Closed",
      whatsappBtn: "WhatsApp",
      callBtn: "Call",
      mapsBtn: "Open in Google Maps",
    },
    contact: {
      eyebrow: "Book your appointment",
      title1: "Your next cut,",
      titleAccent: "one message away",
      subtitle:
        "Message us on WhatsApp or call us directly. We confirm your appointment within minutes and hold your slot.",
      whatsappBtn: "Book on WhatsApp",
      note: "We usually reply within a few minutes during opening hours",
    },
    footer: {
      tagline: "Barbershop in Tenerife. Cuts, beard and classic shave, with the care you deserve.",
      navTitle: "Navigation",
      contactTitle: "Contact",
      followTitle: "Follow us",
      rights: "All rights reserved.",
      privacy: "Privacy policy",
      legal: "Legal notice",
      nav: [
        { href: "#sobre", label: "About us" },
        { href: "#precios", label: "Prices" },
        { href: "#opiniones", label: "Reviews" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Location" },
        { href: "#contacto", label: "Contact" },
      ],
    },
    days: {
      Lunes: "Monday", Martes: "Tuesday", Miércoles: "Wednesday", Jueves: "Thursday",
      Viernes: "Friday", Sábado: "Saturday", Domingo: "Sunday",
    } as Record<string, string>,
  },

  fr: {
    nav: [
      { href: "#sobre", label: "À propos" },
      { href: "#precios", label: "Tarifs" },
      { href: "#por-que", label: "Pourquoi nous" },
      { href: "#opiniones", label: "Avis" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Accès" },
      { href: "#contacto", label: "Contact" },
    ],
    navReserve: "Réserver",
    navReserveMobile: "Réserver sur WhatsApp",
    floatingWhatsappLabel: "Écrivez-nous sur WhatsApp",
    hero: {
      badge: "Barbier · Tenerife",
      title1: "Entrez. Asseyez-vous.",
      title2: "Ressortez stylé.",
      subtitle1: "Barbier à Tenerife. Coupes, barbe et rasage classique,",
      subtitle2: "avec le soin que vous méritez.",
      ctaReserve: "Réserver",
      ctaWhatsApp: "Réserver sur WhatsApp",
      seePrices: "↓ Voir tous les tarifs",
      badges: ["Coupes et dégradés", "Réservation sur WhatsApp", "Apprécié par nos clients"],
    },
    video: {
      eyebrow: "Sur Instagram",
      title: "Voyez-nous à l'œuvre",
      subtitle:
        "Coupes, dégradés et barbe en vidéo. Jetez un œil à notre Instagram pour voir notre travail au quotidien.",
      hint: "@edustyle4 sur Instagram",
      cta: "Voir sur Instagram",
    },
    about: {
      eyebrow: "À propos de nous",
      title: "Ce n'est pas qu'une coupe. C'est votre image.",
      p1: "Chez Eduardo Style, chaque client est traité comme il le mérite : sans précipitation, en écoutant ce que vous recherchez et en soignant chaque détail. Coupes de cheveux, taille de barbe, rasage classique au coupe-chou et dessins personnalisés, le tout dans une ambiance conviviale et détendue.",
      p2: "Que vous veniez pour votre coupe habituelle ou pour changer complètement de style, nous vous conseillons ce qui vous va le mieux et le réalisons avec la technique et le soin que mérite votre image.",
      p3strong: "Réserver est simple : un message WhatsApp suffit.",
      values: [
        { icon: "UserCog", title: "Savoir-faire", description: "Des années derrière le fauteuil. Chaque coupe, chaque barbe et chaque dégradé réalisés avec technique et précision." },
        { icon: "HeartHandshake", title: "Proximité", description: "Ici, vous n'êtes pas un numéro. Nous vous écoutons, comprenons votre style et vous conseillons ce qui vous va vraiment bien." },
        { icon: "Sparkles", title: "Le détail", description: "Serviette chaude, lignes nettes et finitions soignées. Vous repartez avec la sensation d'avoir été vraiment pris en charge." },
      ],
    },
    whyUs: {
      eyebrow: "Pourquoi Eduardo Style",
      title: "Quatre raisons de vous asseoir dans notre fauteuil",
      reasons: [
        { icon: "Scissors", title: "Des coupes sur mesure", description: "Dégradés, classiques, dessins et barbe travaillée. Nous adaptons chaque coupe à votre type de cheveux et à votre style." },
        { icon: "CalendarCheck", title: "Réservez sans appeler", description: "Demandez votre rendez-vous sur WhatsApp quand vous voulez, même en dehors des horaires. Confirmation en quelques minutes." },
        { icon: "Star", title: "Des clients fidèles", description: "La plupart de ceux qui essaient Eduardo Style reviennent. Bon accueil, bonne ambiance et un résultat qui se voit." },
        { icon: "MapPin", title: "À Tenerife, près de chez vous", description: "Facile à trouver, avec cette ambiance de barbier de quartier où l'on se sent comme à la maison." },
      ],
    },
    testimonials: {
      eyebrow: "Avis",
      title: "Ce que disent nos clients",
      badge: "Avis vérifiés Google",
      items: [
        { name: "Carlos M.", rating: 5, text: "Le meilleur barbier du coin. Je repars toujours avec la coupe parfaite et une barbe impeccable. Accueil top et très bonne ambiance.", service: "Coupe + Barbe" },
        { name: "Javi R.", rating: 5, text: "Je viens ici depuis des mois et je ne changerai pas. Bon dégradé, pas d'attente si on réserve sur WhatsApp, toujours bonne humeur.", service: "Dégradé" },
        { name: "Airam G.", rating: 5, text: "Le rasage au coupe-chou avec serviette chaude, c'est un autre niveau. On ressort comme neuf. Vivement recommandé, ça se voit que c'est du métier.", service: "Rasage au coupe-chou" },
        { name: "Dani P.", rating: 5, text: "Professionnel et chaleureux. Il conseille vraiment ce qui vous va, pas seulement ce qu'on demande. Je reviendrai c'est sûr.", service: "Coupe de cheveux" },
        { name: "Miguel Á.", rating: 5, text: "J'y amène mon fils, il a une patience énorme avec les petits. Coupe top et sans drame. Un dix sur dix.", service: "Coupe enfant" },
        { name: "Rubén S.", rating: 5, text: "Qualité, bon prix et bonne ambiance. On sent qu'il aime ce qu'il fait. C'est devenu mon barbier attitré.", service: "Coupe + Barbe" },
      ],
    },
    prices: {
      eyebrow: "Tarifs",
      title: "Des prix clairs. Sans surprise.",
      subtitle:
        "Voici nos services et nos tarifs. Un doute sur ce dont vous avez besoin ? Écrivez-nous, on vous conseille.",
      note: "Les prix peuvent varier selon la longueur et le type de cheveux. Un doute ? Demandez-nous sans engagement.",
      cta: "Réservez votre rendez-vous sur WhatsApp",
      groups: [
        { title: "Coupes", items: [
          { name: "Coupe enfant", desc: "Jusqu'à 8 ans", price: "10 €" },
          { name: "Coupe homme", desc: "Aux ciseaux ou à la tondeuse", price: "13 €" },
          { name: "Coupe + shampoing", desc: "Avec shampoing et coiffage", price: "15 €" },
        ] },
        { title: "Coupe et barbe", items: [
          { name: "Barbe à la tondeuse", desc: "Entretien rapide", price: "5 €" },
          { name: "Barbe : rasage ou contour", desc: "Avec serviette chaude", price: "10 €" },
          { name: "Coupe + barbe", desc: "La plus demandée", price: "20 €", highlight: true },
          { name: "Coupe + barbe + shampoing", desc: "Shampoing inclus", price: "23 €" },
          { name: "Coupe + barbe premium", desc: "Avec couleur, mèches ou extras", price: "25 €" },
          { name: "Formule complète", desc: "Coupe, barbe, cire nez et oreilles, shampoing, nettoyage du visage et massage", price: "40 €" },
        ] },
        { title: "Couleur, mèches et extras", items: [
          { name: "Couleur de barbe", desc: "", price: "15 €" },
          { name: "Couleur de cheveux", desc: "", price: "20 €" },
          { name: "Mèches", desc: "", price: "25 €" },
          { name: "Mèches + couleur", desc: "", price: "35 €" },
          { name: "Décoloration + nuance", desc: "", price: "30 €" },
          { name: "Double décoloration + nuance", desc: "", price: "40 €" },
          { name: "Cire nez et oreilles", desc: "", price: "5 €" },
          { name: "Shampoing", desc: "", price: "3 €" },
        ] },
      ],
    },
    faq: {
      eyebrow: "Questions fréquentes",
      title: "Questions fréquentes. Réponses claires.",
      subtitle:
        "Réponses rapides aux questions les plus posées. Vous ne trouvez pas ce que vous cherchez ? Écrivez-nous sur WhatsApp.",
      items: [
        { question: "Dois-je prendre rendez-vous ou puis-je venir directement ?", answer: "Vous pouvez venir sans rendez-vous, mais pour éviter l'attente nous vous recommandons de réserver sur WhatsApp. Nous confirmons l'heure en quelques minutes et vous gardons votre créneau." },
        { question: "Comment réserver un rendez-vous ?", answer: "Le plus rapide est WhatsApp au +34 694 20 07 78. Vous pouvez aussi nous appeler directement. Nous répondons généralement en quelques minutes pendant les horaires d'ouverture." },
        { question: "Combien coûte une coupe ?", answer: "Une coupe homme coûte 13 € et la formule coupe + barbe 20 €. Pour les enfants, 10 €. Retrouvez la liste complète dans la section Tarifs. Le prix final peut varier selon la longueur des cheveux." },
        { question: "Faites-vous les coupes pour enfants ?", answer: "Oui. Nous coupons les cheveux des enfants avec beaucoup de patience et de bonne humeur, pour que ce soit facile et agréable aussi pour les plus petits." },
        { question: "Faites-vous le rasage au coupe-chou ?", answer: "Oui. Nous proposons le rasage classique au coupe-chou avec serviette chaude : net, relaxant et avec une finition parfaite. Un classique qui vaut vraiment le détour." },
        { question: "Quels moyens de paiement acceptez-vous ?", answer: "Nous acceptons les paiements en espèces et par carte, selon ce qui vous arrange le mieux." },
        { question: "Où êtes-vous situés et quels sont vos horaires ?", answer: "Nous sommes à Los Abrigos, dans le sud de Tenerife, Calle La Marina, Local 1 (38618). Horaires : du lundi au vendredi de 10h00 à 19h00, le samedi de 10h00 à 16h00. Fermé le dimanche." },
      ],
    },
    location: {
      eyebrow: "Comment venir",
      title: "Venez nous voir",
      subtitle: "Nous sommes à Tenerife, facile à trouver. Passez nous voir ou réservez à l'avance pour ne pas attendre.",
      addressLabel: "Adresse",
      phoneLabel: "Téléphone",
      hoursLabel: "Horaires",
      closed: "Fermé",
      whatsappBtn: "WhatsApp",
      callBtn: "Appeler",
      mapsBtn: "Ouvrir dans Google Maps",
    },
    contact: {
      eyebrow: "Réservez votre rendez-vous",
      title1: "Votre prochaine coupe,",
      titleAccent: "à un message près",
      subtitle:
        "Écrivez-nous sur WhatsApp ou appelez-nous directement. Nous confirmons votre rendez-vous en quelques minutes et réservons votre créneau.",
      whatsappBtn: "Réserver sur WhatsApp",
      note: "Nous répondons généralement en quelques minutes pendant les horaires d'ouverture",
    },
    footer: {
      tagline: "Barbier à Tenerife. Coupes, barbe et rasage classique, avec le soin que vous méritez.",
      navTitle: "Navigation",
      contactTitle: "Contact",
      followTitle: "Suivez-nous",
      rights: "Tous droits réservés.",
      privacy: "Politique de confidentialité",
      legal: "Mentions légales",
      nav: [
        { href: "#sobre", label: "À propos" },
        { href: "#precios", label: "Tarifs" },
        { href: "#opiniones", label: "Avis" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Accès" },
        { href: "#contacto", label: "Contact" },
      ],
    },
    days: {
      Lunes: "Lundi", Martes: "Mardi", Miércoles: "Mercredi", Jueves: "Jeudi",
      Viernes: "Vendredi", Sábado: "Samedi", Domingo: "Dimanche",
    } as Record<string, string>,
  },

  de: {
    nav: [
      { href: "#sobre", label: "Über uns" },
      { href: "#precios", label: "Preise" },
      { href: "#por-que", label: "Warum wir" },
      { href: "#opiniones", label: "Bewertungen" },
      { href: "#preguntas", label: "FAQ" },
      { href: "#ubicacion", label: "Anfahrt" },
      { href: "#contacto", label: "Kontakt" },
    ],
    navReserve: "Termin buchen",
    navReserveMobile: "Per WhatsApp buchen",
    floatingWhatsappLabel: "Schreiben Sie uns auf WhatsApp",
    hero: {
      badge: "Barbershop · Teneriffa",
      title1: "Reinkommen. Platz nehmen.",
      title2: "Gestylt rausgehen.",
      subtitle1: "Barbershop auf Teneriffa. Haarschnitt, Bart und klassische Rasur,",
      subtitle2: "mit der Sorgfalt, die Sie verdienen.",
      ctaReserve: "Jetzt buchen",
      ctaWhatsApp: "Per WhatsApp buchen",
      seePrices: "↓ Alle Preise ansehen",
      badges: ["Schnitte & Fades", "Buchung per WhatsApp", "Von Kunden geschätzt"],
    },
    video: {
      eyebrow: "Auf Instagram",
      title: "Sehen Sie uns bei der Arbeit",
      subtitle:
        "Schnitte, Fades und Bartpflege im Video. Schauen Sie auf unserem Instagram vorbei und sehen Sie, wie wir arbeiten.",
      hint: "@edustyle4 auf Instagram",
      cta: "Auf Instagram ansehen",
    },
    about: {
      eyebrow: "Über uns",
      title: "Es ist nicht nur ein Haarschnitt. Es ist Ihr Look.",
      p1: "Bei Eduardo Style wird jeder Kunde so behandelt, wie er es verdient: ohne Eile, mit einem offenen Ohr für Ihre Wünsche und mit Liebe zum Detail. Haarschnitte, Bartpflege, klassische Rasur mit dem Rasiermesser und individuelle Designs, alles in entspannter, familiärer Atmosphäre.",
      p2: "Ob Sie für Ihren gewohnten Schnitt kommen oder komplett neu aussehen möchten: Wir beraten Sie, was am besten zu Ihnen passt, und setzen es mit der Technik und Sorgfalt um, die Ihr Look verdient.",
      p3strong: "Buchen ist einfach: eine WhatsApp-Nachricht genügt.",
      values: [
        { icon: "UserCog", title: "Handwerk", description: "Jahrelange Erfahrung auf dem Stuhl. Jeder Schnitt, jeder Bart und jeder Fade mit Technik und ruhiger Hand." },
        { icon: "HeartHandshake", title: "Nähe", description: "Hier sind Sie keine Nummer. Wir hören zu, verstehen Ihren Stil und beraten Sie ehrlich, was wirklich zu Ihnen passt." },
        { icon: "Sparkles", title: "Liebe zum Detail", description: "Warmes Handtuch, saubere Linien und sorgfältige Finishes. Sie gehen mit dem Gefühl, wirklich umsorgt worden zu sein." },
      ],
    },
    whyUs: {
      eyebrow: "Warum Eduardo Style",
      title: "Vier Gründe, bei uns Platz zu nehmen",
      reasons: [
        { icon: "Scissors", title: "Schnitte nach Maß", description: "Fades, Klassiker, Designs und ausgearbeiteter Bart. Wir passen jeden Schnitt an Ihren Haartyp und Stil an." },
        { icon: "CalendarCheck", title: "Buchen ohne Anruf", description: "Fordern Sie Ihren Termin jederzeit per WhatsApp an, auch außerhalb der Öffnungszeiten. Bestätigung in wenigen Minuten." },
        { icon: "Star", title: "Kunden, die wiederkommen", description: "Die meisten, die Eduardo Style ausprobieren, kommen wieder. Guter Service, gute Atmosphäre und ein Ergebnis, das man sieht." },
        { icon: "MapPin", title: "Direkt hier auf Teneriffa", description: "Leicht zu finden, mit dem Gefühl eines Barbershops von nebenan, in dem man sich wie zuhause fühlt." },
      ],
    },
    testimonials: {
      eyebrow: "Bewertungen",
      title: "Was unsere Kunden sagen",
      badge: "Verifizierte Google-Bewertungen",
      items: [
        { name: "Carlos M.", rating: 5, text: "Der beste Barbier der Gegend. Ich gehe immer mit dem perfekten Schnitt und makellosem Bart. Top Service und tolle Atmosphäre.", service: "Schnitt + Bart" },
        { name: "Javi R.", rating: 5, text: "Ich komme seit Monaten hierher und wechsle nicht mehr. Toller Fade, keine Wartezeit bei Buchung per WhatsApp, immer gute Stimmung.", service: "Fade" },
        { name: "Airam G.", rating: 5, text: "Die Rasur mit dem Rasiermesser und warmem Handtuch ist nochmal eine andere Liga. Man fühlt sich wie neu. Sehr empfehlenswert, man merkt das Handwerk.", service: "Rasur mit dem Rasiermesser" },
        { name: "Dani P.", rating: 5, text: "Professionell und freundlich. Er berät, was wirklich zu einem passt, nicht nur, was man verlangt. Komme auf jeden Fall wieder.", service: "Haarschnitt" },
        { name: "Miguel Á.", rating: 5, text: "Ich bringe meinen Sohn mit, und er hat unglaublich viel Geduld mit den Kleinen. Toller Schnitt, ohne Drama. Zehn von zehn Punkten.", service: "Kinderhaarschnitt" },
        { name: "Rubén S.", rating: 5, text: "Qualität, guter Preis und gute Stimmung. Man merkt, dass er seine Arbeit liebt. Jetzt mein Stammbarbier.", service: "Schnitt + Bart" },
      ],
    },
    prices: {
      eyebrow: "Preise",
      title: "Klare Preise. Keine Überraschungen.",
      subtitle:
        "Das sind unsere Leistungen und Preise. Nicht sicher, was Sie brauchen? Schreiben Sie uns, wir beraten Sie.",
      note: "Die Preise können je nach Haarlänge und -typ variieren. Unsicher? Fragen Sie uns einfach, ganz unverbindlich.",
      cta: "Termin per WhatsApp buchen",
      groups: [
        { title: "Haarschnitte", items: [
          { name: "Kinderhaarschnitt", desc: "Bis 8 Jahre", price: "10 €" },
          { name: "Herrenhaarschnitt", desc: "Mit Schere oder Maschine", price: "13 €" },
          { name: "Schnitt + Waschen", desc: "Mit Waschen und Styling", price: "15 €" },
        ] },
        { title: "Schnitt & Bart", items: [
          { name: "Bart mit Maschine", desc: "Schnelle Auffrischung", price: "5 €" },
          { name: "Bart: Rasur oder Konturen", desc: "Mit warmem Handtuch", price: "10 €" },
          { name: "Schnitt + Bart", desc: "Am meisten gebucht", price: "20 €", highlight: true },
          { name: "Schnitt + Bart + Waschen", desc: "Inklusive Waschen", price: "23 €" },
          { name: "Premium Schnitt + Bart", desc: "Mit Farbe, Strähnen oder Extras", price: "25 €" },
          { name: "Komplettpaket", desc: "Schnitt, Bart, Nasen- und Ohrenwachs, Waschen, Gesichtsreinigung und Massage", price: "40 €" },
        ] },
        { title: "Farbe, Strähnen & Extras", items: [
          { name: "Bartfarbe", desc: "", price: "15 €" },
          { name: "Haarfarbe", desc: "", price: "20 €" },
          { name: "Strähnen", desc: "", price: "25 €" },
          { name: "Strähnen + Farbe", desc: "", price: "35 €" },
          { name: "Blondierung + Tönung", desc: "", price: "30 €" },
          { name: "Doppelte Blondierung + Tönung", desc: "", price: "40 €" },
          { name: "Nasen- und Ohrenwachs", desc: "", price: "5 €" },
          { name: "Waschen", desc: "", price: "3 €" },
        ] },
      ],
    },
    faq: {
      eyebrow: "Häufige Fragen",
      title: "Häufige Fragen. Klare Antworten.",
      subtitle:
        "Schnelle Antworten auf die häufigsten Fragen. Nicht gefunden, was Sie suchen? Schreiben Sie uns per WhatsApp.",
      items: [
        { question: "Brauche ich einen Termin oder kann ich einfach vorbeikommen?", answer: "Sie können gerne ohne Termin vorbeikommen, aber um Wartezeit zu vermeiden, empfehlen wir eine Buchung per WhatsApp. Wir bestätigen Ihre Zeit innerhalb von Minuten und reservieren Ihren Platz." },
        { question: "Wie buche ich einen Termin?", answer: "Am schnellsten geht es per WhatsApp unter +34 694 20 07 78. Sie können uns auch direkt anrufen. Wir antworten während der Öffnungszeiten meist innerhalb weniger Minuten." },
        { question: "Was kostet ein Haarschnitt?", answer: "Ein Herrenhaarschnitt kostet 13 € und das Paket Schnitt + Bart 20 €. Für Kinder 10 €. Die vollständige Liste finden Sie im Bereich Preise. Der Endpreis kann je nach Haarlänge variieren." },
        { question: "Schneiden Sie auch Kinderhaare?", answer: "Ja. Wir schneiden Kinderhaare mit viel Geduld und guter Atmosphäre, damit es auch für die Kleinsten einfach und angenehm ist." },
        { question: "Bieten Sie Rasur mit dem Rasiermesser an?", answer: "Ja. Wir bieten die klassische Rasur mit dem Rasiermesser und warmem Handtuch: gründlich, entspannend und mit perfektem Finish. Ein Klassiker, den man ausprobiert haben sollte." },
        { question: "Welche Zahlungsmethoden akzeptieren Sie?", answer: "Wir akzeptieren Barzahlung und Kartenzahlung, ganz wie es Ihnen am liebsten ist." },
        { question: "Wo befindet ihr euch und welche Öffnungszeiten habt ihr?", answer: "Wir befinden uns in Los Abrigos, im Süden von Teneriffa, Calle La Marina, Local 1 (38618). Öffnungszeiten: Montag bis Freitag 10:00–19:00 Uhr, Samstag 10:00–16:00 Uhr. Sonntags geschlossen." },
      ],
    },
    location: {
      eyebrow: "Anfahrt",
      title: "Besuchen Sie uns",
      subtitle: "Wir sind auf Teneriffa, leicht zu finden. Kommen Sie vorbei oder buchen Sie vorab, damit Sie nicht warten müssen.",
      addressLabel: "Adresse",
      phoneLabel: "Telefon",
      hoursLabel: "Öffnungszeiten",
      closed: "Geschlossen",
      whatsappBtn: "WhatsApp",
      callBtn: "Anrufen",
      mapsBtn: "In Google Maps öffnen",
    },
    contact: {
      eyebrow: "Termin buchen",
      title1: "Ihr nächster Schnitt,",
      titleAccent: "nur eine Nachricht entfernt",
      subtitle:
        "Schreiben Sie uns per WhatsApp oder rufen Sie uns direkt an. Wir bestätigen Ihren Termin innerhalb weniger Minuten und reservieren Ihren Platz.",
      whatsappBtn: "Per WhatsApp buchen",
      note: "Wir antworten während der Öffnungszeiten meist innerhalb weniger Minuten",
    },
    footer: {
      tagline: "Barbershop auf Teneriffa. Haarschnitt, Bart und klassische Rasur, mit der Sorgfalt, die Sie verdienen.",
      navTitle: "Navigation",
      contactTitle: "Kontakt",
      followTitle: "Folgen Sie uns",
      rights: "Alle Rechte vorbehalten.",
      privacy: "Datenschutzerklärung",
      legal: "Impressum",
      nav: [
        { href: "#sobre", label: "Über uns" },
        { href: "#precios", label: "Preise" },
        { href: "#opiniones", label: "Bewertungen" },
        { href: "#preguntas", label: "FAQ" },
        { href: "#ubicacion", label: "Anfahrt" },
        { href: "#contacto", label: "Kontakt" },
      ],
    },
    days: {
      Lunes: "Montag", Martes: "Dienstag", Miércoles: "Mittwoch", Jueves: "Donnerstag",
      Viernes: "Freitag", Sábado: "Samstag", Domingo: "Sonntag",
    } as Record<string, string>,
  },
} as const;

export function getContent(lang: Lang) {
  return content[lang];
}
